using L5Sharp.Components;

namespace L5Sharp.Enums;

/// <summary>
/// An enumeration of all Logix Routine types.
/// </summary>
/// <remarks>
/// Routine type indicates what programming style/language the <see cref="Routine"/> object contains.
/// The type of routine will determine what <see cref="LogixContent"/> is generated by the routine object.
/// </remarks>
public sealed class RoutineType : LogixEnum<RoutineType, string>
{
    private RoutineType(string name, string value) : base(name, value)
    {
    }

    /// <summary>
    /// Represents no <see cref="RoutineType"/> value.
    /// </summary>
    public static readonly RoutineType Typeless = new(nameof(Typeless), nameof(Typeless));
        
    /// <summary>
    /// Represents a Relay Ladder Logic routine type. 
    /// </summary>
    public static readonly RoutineType RLL = new(nameof(RLL), nameof(RLL));
        
    /// <summary>
    /// Represents a Function Block Diagram routine type. 
    /// </summary>
    public static readonly RoutineType FBD = new(nameof(FBD), nameof(FBD));
        
    /// <summary>
    /// Represents a Sequential Function Chart routine type. 
    /// </summary>
    public static readonly RoutineType SFC = new(nameof(SFC), nameof(SFC));
        
    /// <summary>
    /// Represents a Structured Text routine type.
    /// </summary>
    public static readonly RoutineType ST = new(nameof(ST), nameof(ST));
}