// ReSharper disable InconsistentNaming

namespace L5Sharp;

/// <summary>
/// A static class of L5X element and attribute names that provide string reference to L5X names so to avoid using
/// magic string. This class was generated by querying a L5X file, therefore it may not be all inclusive. 
/// </summary>
public static class L5XName
{
    ///<summary>
    /// Gets the <c>AckRequired</c> L5X name value.
    ///</summary>
    public const string AckRequired = "AckRequired";
        
    ///<summary>
    /// Gets the <c>AdditionalHelpText</c> L5X name value.
    ///</summary>
    public const string AdditionalHelpText = "AdditionalHelpText";
        
    ///<summary>
    /// Gets the <c>AddOnInstructionDefinition</c> L5X name value.
    ///</summary>
    public const string AddOnInstructionDefinition = "AddOnInstructionDefinition";
        
    ///<summary>
    /// Gets the <c>AddOnInstructionDefinitions</c> L5X name value.
    ///</summary>
    public const string AddOnInstructionDefinitions = "AddOnInstructionDefinitions";
        
    ///<summary>
    /// Gets the <c>Address</c> L5X name value.
    ///</summary>
    public const string Address = "Address";
        
    ///<summary>
    /// Gets the <c>AlarmAnalogParameters</c> L5X name value.
    ///</summary>
    public const string AlarmAnalogParameters = "AlarmAnalogParameters";
        
    ///<summary>
    /// Gets the <c>AlarmConfig</c> L5X name value.
    ///</summary>
    public const string AlarmConfig = "AlarmConfig";
        
    ///<summary>
    /// Gets the <c>AlarmCountReset</c> L5X name value.
    ///</summary>
    public const string AlarmCountReset = "AlarmCountReset";
        
    ///<summary>
    /// Gets the <c>AlarmDigitalParameters</c> L5X name value.
    ///</summary>
    public const string AlarmDigitalParameters = "AlarmDigitalParameters";
        
    ///<summary>
    /// Gets the <c>AliasFor</c> L5X name value.
    ///</summary>
    public const string AliasFor = "AliasFor";
        
    ///<summary>
    /// Gets the <c>Array</c> L5X name value.
    ///</summary>
    public const string Array = "Array";
        
    ///<summary>
    /// Gets the <c>ArrayMember</c> L5X name value.
    ///</summary>
    public const string ArrayMember = "ArrayMember";
        
    ///<summary>
    /// Gets the <c>AttributeNumber</c> L5X name value.
    ///</summary>
    public const string AttributeNumber = "AttributeNumber";
        
    ///<summary>
    /// Gets the <c>BitNumber</c> L5X name value.
    ///</summary>
    public const string BitNumber = "BitNumber";
        
    ///<summary>
    /// Gets the <c>Bus</c> L5X name value.
    ///</summary>
    public const string Bus = "Bus";
        
    ///<summary>
    /// Gets the <c>CacheConnections</c> L5X name value.
    ///</summary>
    public const string CacheConnections = "CacheConnections";
        
    ///<summary>
    /// Gets the <c>CanUseRPIFromProducer</c> L5X name value.
    ///</summary>
    public const string CanUseRpiFromProducer = "CanUseRPIFromProducer";
        
    ///<summary>
    /// Gets the <c>CatalogNumber</c> L5X name value.
    ///</summary>
    public const string CatalogNumber = "CatalogNumber";
        
    ///<summary>
    /// Gets the <c>CatNum</c> L5X name value.
    ///</summary>
    public const string CatNum = "CatNum";
        
    ///<summary>
    /// Gets the <c>ChangesToDetect</c> L5X name value.
    ///</summary>
    public const string ChangesToDetect = "ChangesToDetect";
        
    ///<summary>
    /// Gets the <c>ChildProgram</c> L5X name value.
    ///</summary>
    public const string ChildProgram = "ChildProgram";
        
    ///<summary>
    /// Gets the <c>ChildPrograms</c> L5X name value.
    ///</summary>
    public const string ChildPrograms = "ChildPrograms";
        
    ///<summary>
    /// Gets the <c>Class</c> L5X name value.
    ///</summary>
    public const string Class = "Class";
        
    ///<summary>
    /// Gets the <c>Code</c> L5X name value.
    ///</summary>
    public const string Code = "Code";
        
    ///<summary>
    /// Gets the <c>Comment</c> L5X name value.
    ///</summary>
    public const string Comment = "Comment";
        
    ///<summary>
    /// Gets the <c>Comments</c> L5X name value.
    ///</summary>
    public const string Comments = "Comments";
        
    ///<summary>
    /// Gets the <c>CommMethod</c> L5X name value.
    ///</summary>
    public const string CommMethod = "CommMethod";
        
    ///<summary>
    /// Gets the <c>CommTypeCode</c> L5X name value.
    ///</summary>
    public const string CommTypeCode = "CommTypeCode";
        
    ///<summary>
    /// Gets the <c>Communications</c> L5X name value.
    ///</summary>
    public const string Communications = "Communications";
        
    ///<summary>
    /// Gets the <c>Condition</c> L5X name value.
    ///</summary>
    public const string Condition = "Condition";
        
    ///<summary>
    /// Gets the <c>ConfigData</c> L5X name value.
    ///</summary>
    public const string ConfigData = "ConfigData";
        
    ///<summary>
    /// Gets the <c>ConfigID</c> L5X name value.
    ///</summary>
    public const string ConfigId = "ConfigID";
        
    ///<summary>
    /// Gets the <c>ConfigScript</c> L5X name value.
    ///</summary>
    public const string ConfigScript = "ConfigScript";
        
    ///<summary>
    /// Gets the <c>ConfigSize</c> L5X name value.
    ///</summary>
    public const string ConfigSize = "ConfigSize";
        
    ///<summary>
    /// Gets the <c>ConfigTag</c> L5X name value.
    ///</summary>
    public const string ConfigTag = "ConfigTag";
        
    ///<summary>
    /// Gets the <c>ConnectedFlag</c> L5X name value.
    ///</summary>
    public const string ConnectedFlag = "ConnectedFlag";
        
    ///<summary>
    /// Gets the <c>Connection</c> L5X name value.
    ///</summary>
    public const string Connection = "Connection";
        
    ///<summary>
    /// Gets the <c>ConnectionPath</c> L5X name value.
    ///</summary>
    public const string ConnectionPath = "ConnectionPath";
        
    ///<summary>
    /// Gets the <c>Connections</c> L5X name value.
    ///</summary>
    public const string Connections = "Connections";
        
    ///<summary>
    /// Gets the <c>Constant</c> L5X name value.
    ///</summary>
    public const string Constant = "Constant";
        
    ///<summary>
    /// Gets the <c>ContainsContext</c> L5X name value.
    ///</summary>
    public const string ContainsContext = "ContainsContext";
        
    ///<summary>
    /// Gets the <c>Controller</c> L5X name value.
    ///</summary>
    public const string Controller = "Controller";
        
    ///<summary>
    /// Gets the <c>CreatedBy</c> L5X name value.
    ///</summary>
    public const string CreatedBy = "CreatedBy";
        
    ///<summary>
    /// Gets the <c>CreatedDate</c> L5X name value.
    ///</summary>
    public const string CreatedDate = "CreatedDate";
        
    ///<summary>
    /// Gets the <c>CST</c> L5X name value.
    ///</summary>
    public const string Cst = "CST";
        
    ///<summary>
    /// Gets the <c>Data</c> L5X name value.
    ///</summary>
    public const string Data = "Data";
        
    ///<summary>
    /// Gets the <c>DataLogs</c> L5X name value.
    ///</summary>
    public const string DataLogs = "DataLogs";
        
    ///<summary>
    /// Gets the <c>DataType</c> L5X name value.
    ///</summary>
    public const string DataType = "DataType";
        
    ///<summary>
    /// Gets the <c>DataTypes</c> L5X name value.
    ///</summary>
    public const string DataTypes = "DataTypes";
        
    ///<summary>
    /// Gets the <c>DataValue</c> L5X name value.
    ///</summary>
    public const string DataValue = "DataValue";
        
    ///<summary>
    /// Gets the <c>DataValueMember</c> L5X name value.
    ///</summary>
    public const string DataValueMember = "DataValueMember";
        
    ///<summary>
    /// Gets the <c>Deadband</c> L5X name value.
    ///</summary>
    public const string Deadband = "Deadband";
        
    ///<summary>
    /// Gets the <c>DefaultData</c> L5X name value.
    ///</summary>
    public const string DefaultData = "DefaultData";
        
    ///<summary>
    /// Gets the <c>Description</c> L5X name value.
    ///</summary>
    public const string Description = "Description";
        
    ///<summary>
    /// Gets the <c>DestinationTag</c> L5X name value.
    ///</summary>
    public const string DestinationTag = "DestinationTag";
        
    ///<summary>
    /// Gets the <c>Dimension</c> L5X name value.
    ///</summary>
    public const string Dimension = "Dimension";
        
    ///<summary>
    /// Gets the <c>Dimensions</c> L5X name value.
    ///</summary>
    public const string Dimensions = "Dimensions";
        
    ///<summary>
    /// Gets the <c>Disabled</c> L5X name value.
    ///</summary>
    public const string Disabled = "Disabled";
        
    ///<summary>
    /// Gets the <c>DisableUpdateOutputs</c> L5X name value.
    ///</summary>
    public const string DisableUpdateOutputs = "DisableUpdateOutputs";
        
    ///<summary>
    /// Gets the <c>DownloadProjectCustomProperties</c> L5X name value.
    ///</summary>
    public const string DownloadProjectCustomProperties = "DownloadProjectCustomProperties";
        
    ///<summary>
    /// Gets the <c>DownloadProjectDocumentationAndExtendedProperties</c> L5X name value.
    ///</summary>
    public const string DownloadProjectDocumentationAndExtendedProperties = "DownloadProjectDocumentationAndExtendedProperties";
        
    ///<summary>
    /// Gets the <c>DrivesADCEnabled</c> L5X name value.
    ///</summary>
    public const string DrivesAdcEnabled = "DrivesADCEnabled";
        
    ///<summary>
    /// Gets the <c>DrivesADCMode</c> L5X name value.
    ///</summary>
    public const string DrivesAdcMode = "DrivesADCMode";
        
    ///<summary>
    /// Gets the <c>EditedBy</c> L5X name value.
    ///</summary>
    public const string EditedBy = "EditedBy";
        
    ///<summary>
    /// Gets the <c>EditedDate</c> L5X name value.
    ///</summary>
    public const string EditedDate = "EditedDate";
        
    ///<summary>
    /// Gets the <c>EKey</c> L5X name value.
    ///</summary>
    public const string EKey = "EKey";
        
    ///<summary>
    /// Gets the <c>Element</c> L5X name value.
    ///</summary>
    public const string Element = "Element";
        
    ///<summary>
    /// Gets the <c>Enabled</c> L5X name value.
    ///</summary>
    public const string Enabled = "Enabled";
        
    ///<summary>
    /// Gets the <c>EnableIn</c> L5X name value.
    ///</summary>
    public const string EnableIn = "EnableIn";
        
    ///<summary>
    /// Gets the <c>EnableTimeout</c> L5X name value.
    ///</summary>
    public const string EnableTimeout = "EnableTimeout";
        
    ///<summary>
    /// Gets the <c>EncodedData</c> L5X name value.
    ///</summary>
    public const string EncodedData = "EncodedData";
        
    ///<summary>
    /// Gets the <c>EncodedType</c> L5X name value.
    ///</summary>
    public const string EncodedType = "EncodedType";
        
    ///<summary>
    /// Gets the <c>EncryptionConfig</c> L5X name value.
    ///</summary>
    public const string EncryptionConfig = "EncryptionConfig";
        
    ///<summary>
    /// Gets the <c>EngineeringUnit</c> L5X name value.
    ///</summary>
    public const string EngineeringUnit = "EngineeringUnit";
        
    ///<summary>
    /// Gets the <c>EngineeringUnits</c> L5X name value.
    ///</summary>
    public const string EngineeringUnits = "EngineeringUnits";
        
    ///<summary>
    /// Gets the <c>EthernetPort</c> L5X name value.
    ///</summary>
    public const string EthernetPort = "EthernetPort";
        
    ///<summary>
    /// Gets the <c>EthernetPorts</c> L5X name value.
    ///</summary>
    public const string EthernetPorts = "EthernetPorts";
        
    ///<summary>
    /// Gets the <c>EventID</c> L5X name value.
    ///</summary>
    public const string EventId = "EventID";
        
    ///<summary>
    /// Gets the <c>EventInfo</c> L5X name value.
    ///</summary>
    public const string EventInfo = "EventInfo";
        
    ///<summary>
    /// Gets the <c>EventTag</c> L5X name value.
    ///</summary>
    public const string EventTag = "EventTag";
        
    ///<summary>
    /// Gets the <c>EventTrigger</c> L5X name value.
    ///</summary>
    public const string EventTrigger = "EventTrigger";
        
    ///<summary>
    /// Gets the <c>ExecuteEnableInFalse</c> L5X name value.
    ///</summary>
    public const string ExecuteEnableInFalse = "ExecuteEnableInFalse";
        
    ///<summary>
    /// Gets the <c>ExecutePostscan</c> L5X name value.
    ///</summary>
    public const string ExecutePostscan = "ExecutePostscan";
        
    ///<summary>
    /// Gets the <c>ExecutePrescan</c> L5X name value.
    ///</summary>
    public const string ExecutePrescan = "ExecutePrescan";
        
    ///<summary>
    /// Gets the <c>ExportDate</c> L5X name value.
    ///</summary>
    public const string ExportDate = "ExportDate";
        
    ///<summary>
    /// Gets the <c>ExportOptions</c> L5X name value.
    ///</summary>
    public const string ExportOptions = "ExportOptions";
        
    ///<summary>
    /// Gets the <c>ExtendedProperties</c> L5X name value.
    ///</summary>
    public const string ExtendedProperties = "ExtendedProperties";
        
    ///<summary>
    /// Gets the <c>ExternalAccess</c> L5X name value.
    ///</summary>
    public const string ExternalAccess = "ExternalAccess";
        
    ///<summary>
    /// Gets the <c>Family</c> L5X name value.
    ///</summary>
    public const string Family = "Family";
        
    ///<summary>
    /// Gets the <c>FaultRoutineName</c> L5X name value.
    ///</summary>
    public const string FaultRoutineName = "FaultRoutineName";
        
    ///<summary>
    /// Gets the <c>Format</c> L5X name value.
    ///</summary>
    public const string Format = "Format";
        
    ///<summary>
    /// Gets the <c>HEnabled</c> L5X name value.
    ///</summary>
    public const string HEnabled = "HEnabled";
        
    ///<summary>
    /// Gets the <c>HHEnabled</c> L5X name value.
    ///</summary>
    public const string HHEnabled = "HHEnabled";
        
    ///<summary>
    /// Gets the <c>HHLimit</c> L5X name value.
    ///</summary>
    public const string HHLimit = "HHLimit";
        
    ///<summary>
    /// Gets the <c>HHMinDurationEnable</c> L5X name value.
    ///</summary>
    public const string HHMinDurationEnable = "HHMinDurationEnable";
        
    ///<summary>
    /// Gets the <c>HHOperAck</c> L5X name value.
    ///</summary>
    public const string HHOperAck = "HHOperAck";
        
    ///<summary>
    /// Gets the <c>HHOperShelve</c> L5X name value.
    ///</summary>
    public const string HHOperShelve = "HHOperShelve";
        
    ///<summary>
    /// Gets the <c>HHOperUnshelve</c> L5X name value.
    ///</summary>
    public const string HHOperUnshelve = "HHOperUnshelve";
        
    ///<summary>
    /// Gets the <c>HHProgAck</c> L5X name value.
    ///</summary>
    public const string HHProgAck = "HHProgAck";
        
    ///<summary>
    /// Gets the <c>HHSeverity</c> L5X name value.
    ///</summary>
    public const string HHSeverity = "HHSeverity";
        
    ///<summary>
    /// Gets the <c>Hidden</c> L5X name value.
    ///</summary>
    public const string Hidden = "Hidden";
        
    ///<summary>
    /// Gets the <c>HLimit</c> L5X name value.
    ///</summary>
    public const string HLimit = "HLimit";
        
    ///<summary>
    /// Gets the <c>HMinDurationEnable</c> L5X name value.
    ///</summary>
    public const string HMinDurationEnable = "HMinDurationEnable";
        
    ///<summary>
    /// Gets the <c>HOperAck</c> L5X name value.
    ///</summary>
    public const string HOperAck = "HOperAck";
        
    ///<summary>
    /// Gets the <c>HOperShelve</c> L5X name value.
    ///</summary>
    public const string HOperShelve = "HOperShelve";
        
    ///<summary>
    /// Gets the <c>HOperUnshelve</c> L5X name value.
    ///</summary>
    public const string HOperUnshelve = "HOperUnshelve";
        
    ///<summary>
    /// Gets the <c>HProgAck</c> L5X name value.
    ///</summary>
    public const string HProgAck = "HProgAck";
        
    ///<summary>
    /// Gets the <c>HSeverity</c> L5X name value.
    ///</summary>
    public const string HSeverity = "HSeverity";
        
    ///<summary>
    /// Gets the <c>Id</c> L5X name value.
    ///</summary>
    public const string Id = "Id";
        
    ///<summary>
    /// Gets the <c>In</c> L5X name value.
    ///</summary>
    public const string In = "In";
        
    ///<summary>
    /// Gets the <c>Index</c> L5X name value.
    ///</summary>
    public const string Index = "Index";
        
    ///<summary>
    /// Gets the <c>InFault</c> L5X name value.
    ///</summary>
    public const string InFault = "InFault";
        
    ///<summary>
    /// Gets the <c>InhibitAutomaticFirmwareUpdate</c> L5X name value.
    ///</summary>
    public const string InhibitAutomaticFirmwareUpdate = "InhibitAutomaticFirmwareUpdate";
        
    ///<summary>
    /// Gets the <c>Inhibited</c> L5X name value.
    ///</summary>
    public const string Inhibited = "Inhibited";
        
    ///<summary>
    /// Gets the <c>InhibitTask</c> L5X name value.
    ///</summary>
    public const string InhibitTask = "InhibitTask";
        
    ///<summary>
    /// Gets the <c>InputConnectionType</c> L5X name value.
    ///</summary>
    public const string InputConnectionType = "InputConnectionType";
        
    ///<summary>
    /// Gets the <c>InputCxnPoint</c> L5X name value.
    ///</summary>
    public const string InputCxnPoint = "InputCxnPoint";
        
    ///<summary>
    /// Gets the <c>InputProductionTrigger</c> L5X name value.
    ///</summary>
    public const string InputProductionTrigger = "InputProductionTrigger";
        
    ///<summary>
    /// Gets the <c>InputSize</c> L5X name value.
    ///</summary>
    public const string InputSize = "InputSize";
        
    ///<summary>
    /// Gets the <c>InputTag</c> L5X name value.
    ///</summary>
    public const string InputTag = "InputTag";
        
    ///<summary>
    /// Gets the <c>InputTagSuffix</c> L5X name value.
    ///</summary>
    public const string InputTagSuffix = "InputTagSuffix";
        
    ///<summary>
    /// Gets the <c>IsEncrypted</c> L5X name value.
    ///</summary>
    public const string IsEncrypted = "IsEncrypted";
        
    ///<summary>
    /// Gets the <c>KeepTestEditsOnSwitchOver</c> L5X name value.
    ///</summary>
    public const string KeepTestEditsOnSwitchOver = "KeepTestEditsOnSwitchOver";
        
    ///<summary>
    /// Gets the <c>Label</c> L5X name value.
    ///</summary>
    public const string Label = "Label";
        
    ///<summary>
    /// Gets the <c>LargePacketUsage</c> L5X name value.
    ///</summary>
    public const string LargePacketUsage = "LargePacketUsage";
        
    ///<summary>
    /// Gets the <c>LastModifiedDate</c> L5X name value.
    ///</summary>
    public const string LastModifiedDate = "LastModifiedDate";
        
    ///<summary>
    /// Gets the <c>Latched</c> L5X name value.
    ///</summary>
    public const string Latched = "Latched";
        
    ///<summary>
    /// Gets the <c>LEnabled</c> L5X name value.
    ///</summary>
    public const string LEnabled = "LEnabled";
        
    ///<summary>
    /// Gets the <c>Length</c> L5X name value.
    ///</summary>
    public const string Length = "Length";
        
    ///<summary>
    /// Gets the <c>Line</c> L5X name value.
    ///</summary>
    public const string Line = "Line";

    ///<summary>
    /// Gets the <c>LLEnabled</c> L5X name value.
    ///</summary>
    public const string LLEnabled = "LLEnabled";
        
    ///<summary>
    /// Gets the <c>LLimit</c> L5X name value.
    ///</summary>
    public const string LLimit = "LLimit";
        
    ///<summary>
    /// Gets the <c>LLLimit</c> L5X name value.
    ///</summary>
    public const string LLLimit = "LLLimit";
        
    ///<summary>
    /// Gets the <c>LLMinDurationEnable</c> L5X name value.
    ///</summary>
    public const string LLMinDurationEnable = "LLMinDurationEnable";
        
    ///<summary>
    /// Gets the <c>LLOperAck</c> L5X name value.
    ///</summary>
    public const string LLOperAck = "LLOperAck";
        
    ///<summary>
    /// Gets the <c>LLOperShelve</c> L5X name value.
    ///</summary>
    public const string LLOperShelve = "LLOperShelve";
        
    ///<summary>
    /// Gets the <c>LLOperUnshelve</c> L5X name value.
    ///</summary>
    public const string LLOperUnshelve = "LLOperUnshelve";
        
    ///<summary>
    /// Gets the <c>LLProgAck</c> L5X name value.
    ///</summary>
    public const string LLProgAck = "LLProgAck";
        
    ///<summary>
    /// Gets the <c>LLSeverity</c> L5X name value.
    ///</summary>
    public const string LLSeverity = "LLSeverity";
        
    ///<summary>
    /// Gets the <c>LMinDurationEnable</c> L5X name value.
    ///</summary>
    public const string LMinDurationEnable = "LMinDurationEnable";
        
    ///<summary>
    /// Gets the <c>LocalElement</c> L5X name value.
    ///</summary>
    public const string LocalElement = "LocalElement";
        
    ///<summary>
    /// Gets the <c>LocalIndex</c> L5X name value.
    ///</summary>
    public const string LocalIndex = "LocalIndex";
        
    ///<summary>
    /// Gets the <c>LocalTag</c> L5X name value.
    ///</summary>
    public const string LocalTag = "LocalTag";
        
    ///<summary>
    /// Gets the <c>LocalTags</c> L5X name value.
    ///</summary>
    public const string LocalTags = "LocalTags";
        
    ///<summary>
    /// Gets the <c>LocalTimeAdjustment</c> L5X name value.
    ///</summary>
    public const string LocalTimeAdjustment = "LocalTimeAdjustment";
        
    ///<summary>
    /// Gets the <c>LOperAck</c> L5X name value.
    ///</summary>
    public const string LOperAck = "LOperAck";
        
    ///<summary>
    /// Gets the <c>LOperShelve</c> L5X name value.
    ///</summary>
    public const string LOperShelve = "LOperShelve";
        
    ///<summary>
    /// Gets the <c>LOperUnshelve</c> L5X name value.
    ///</summary>
    public const string LOperUnshelve = "LOperUnshelve";
        
    ///<summary>
    /// Gets the <c>LProgAck</c> L5X name value.
    ///</summary>
    public const string LProgAck = "LProgAck";
        
    ///<summary>
    /// Gets the <c>LSeverity</c> L5X name value.
    ///</summary>
    public const string LSeverity = "LSeverity";
        
    ///<summary>
    /// Gets the <c>MainRoutineName</c> L5X name value.
    ///</summary>
    public const string MainRoutineName = "MainRoutineName";
        
    ///<summary>
    /// Gets the <c>Major</c> L5X name value.
    ///</summary>
    public const string Major = "Major";
        
    ///<summary>
    /// Gets the <c>MajorFault</c> L5X name value.
    ///</summary>
    public const string MajorFault = "MajorFault";
        
    ///<summary>
    /// Gets the <c>MajorFaultProgram</c> L5X name value.
    ///</summary>
    public const string MajorFaultProgram = "MajorFaultProgram";
        
    ///<summary>
    /// Gets the <c>MajorRev</c> L5X name value.
    ///</summary>
    public const string MajorRev = "MajorRev";
        
    ///<summary>
    /// Gets the <c>MasterID</c> L5X name value.
    ///</summary>
    public const string MasterId = "MasterID";
        
    ///<summary>
    /// Gets the <c>MatchProjectToController</c> L5X name value.
    ///</summary>
    public const string MatchProjectToController = "MatchProjectToController";
        
    ///<summary>
    /// Gets the <c>MaxShelveDuration</c> L5X name value.
    ///</summary>
    public const string MaxShelveDuration = "MaxShelveDuration";
        
    ///<summary>
    /// Gets the <c>Member</c> L5X name value.
    ///</summary>
    public const string Member = "Member";
        
    ///<summary>
    /// Gets the <c>Members</c> L5X name value.
    ///</summary>
    public const string Members = "Members";
        
    ///<summary>
    /// Gets the <c>MessageParameter</c> L5X name value.
    ///</summary>
    public const string MessageParameter = "MessageParameter";
        
    ///<summary>
    /// Gets the <c>MessageParameters</c> L5X name value.
    ///</summary>
    public const string MessageParameters = "MessageParameters";
        
    ///<summary>
    /// Gets the <c>MessageType</c> L5X name value.
    ///</summary>
    public const string MessageType = "MessageType";
        
    ///<summary>
    /// Gets the <c>MinDurationPRE</c> L5X name value.
    ///</summary>
    public const string MinDurationPRE = "MinDurationPRE";
        
    ///<summary>
    /// Gets the <c>Minor</c> L5X name value.
    ///</summary>
    public const string Minor = "Minor";
        
    ///<summary>
    /// Gets the <c>MinorRev</c> L5X name value.
    ///</summary>
    public const string MinorRev = "MinorRev";
        
    ///<summary>
    /// Gets the <c>Module</c> L5X name value.
    ///</summary>
    public const string Module = "Module";
        
    ///<summary>
    /// Gets the <c>Modules</c> L5X name value.
    ///</summary>
    public const string Modules = "Modules";
        
    ///<summary>
    /// Gets the <c>Name</c> L5X name value.
    ///</summary>
    public const string Name = "Name";
        
    ///<summary>
    /// Gets the <c>Number</c> L5X name value.
    ///</summary>
    public const string Number = "Number";
        
    ///<summary>
    /// Gets the <c>ObjectType</c> L5X name value.
    ///</summary>
    public const string ObjectType = "ObjectType";
        
    ///<summary>
    /// Gets the <c>OperAck</c> L5X name value.
    ///</summary>
    public const string OperAck = "OperAck";
        
    ///<summary>
    /// Gets the <c>OperAckAll</c> L5X name value.
    ///</summary>
    public const string OperAckAll = "OperAckAll";
        
    ///<summary>
    /// Gets the <c>Operand</c> L5X name value.
    ///</summary>
    public const string Operand = "Operand";
        
    ///<summary>
    /// Gets the <c>OperDisable</c> L5X name value.
    ///</summary>
    public const string OperDisable = "OperDisable";
        
    ///<summary>
    /// Gets the <c>OperEnable</c> L5X name value.
    ///</summary>
    public const string OperEnable = "OperEnable";
        
    ///<summary>
    /// Gets the <c>OperReset</c> L5X name value.
    ///</summary>
    public const string OperReset = "OperReset";
        
    ///<summary>
    /// Gets the <c>OperShelve</c> L5X name value.
    ///</summary>
    public const string OperShelve = "OperShelve";
        
    ///<summary>
    /// Gets the <c>OperSuppress</c> L5X name value.
    ///</summary>
    public const string OperSuppress = "OperSuppress";
        
    ///<summary>
    /// Gets the <c>OperUnshelve</c> L5X name value.
    ///</summary>
    public const string OperUnshelve = "OperUnshelve";
        
    ///<summary>
    /// Gets the <c>OperUnsuppress</c> L5X name value.
    ///</summary>
    public const string OperUnsuppress = "OperUnsuppress";
        
    ///<summary>
    /// Gets the <c>OutputCxnPoint</c> L5X name value.
    ///</summary>
    public const string OutputCxnPoint = "OutputCxnPoint";
        
    ///<summary>
    /// Gets the <c>OutputRedundantOwner</c> L5X name value.
    ///</summary>
    public const string OutputRedundantOwner = "OutputRedundantOwner";
        
    ///<summary>
    /// Gets the <c>OutputSize</c> L5X name value.
    ///</summary>
    public const string OutputSize = "OutputSize";
        
    ///<summary>
    /// Gets the <c>OutputTag</c> L5X name value.
    ///</summary>
    public const string OutputTag = "OutputTag";
        
    ///<summary>
    /// Gets the <c>OutputTagSuffix</c> L5X name value.
    ///</summary>
    public const string OutputTagSuffix = "OutputTagSuffix";

    ///<summary>
    /// Gets the <c>Owner</c> L5X name value.
    ///</summary>
    public const string Owner = "Owner";
        
    ///<summary>
    /// Gets the <c>Parameter</c> L5X name value.
    ///</summary>
    public const string Parameter = "Parameter";
        
    ///<summary>
    /// Gets the <c>Parameters</c> L5X name value.
    ///</summary>
    public const string Parameters = "Parameters";
        
    ///<summary>
    /// Gets the <c>ParameterConnection</c> L5X name value.
    ///</summary>
    public const string ParameterConnection = "ParameterConnection";
        
    ///<summary>
    /// Gets the <c>ParameterConnections</c> L5X name value.
    ///</summary>
    public const string ParameterConnections = "ParameterConnections";
        
    ///<summary>
    /// Gets the <c>ParentModPortId</c> L5X name value.
    ///</summary>
    public const string ParentModPortId = "ParentModPortId";
        
    ///<summary>
    /// Gets the <c>ParentModule</c> L5X name value.
    ///</summary>
    public const string ParentModule = "ParentModule";
        
    ///<summary>
    /// Gets the <c>PassThroughConfiguration</c> L5X name value.
    ///</summary>
    public const string PassThroughConfiguration = "PassThroughConfiguration";

    ///<summary>
    /// Gets the <c>Port</c> L5X name value.
    ///</summary>
    public const string Port = "Port";

    ///<summary>
    /// Gets the <c>PortEnabled</c> L5X name value.
    ///</summary>
    public const string PortEnabled = "PortEnabled";
        
    ///<summary>
    /// Gets the <c>Ports</c> L5X name value.
    ///</summary>
    public const string Ports = "Ports";
    
    ///<summary>
    /// Gets the <c>PowerLossProgram</c> L5X name value.
    ///</summary>
    public const string PowerLossProgram = "PowerLossProgram";
        
    ///<summary>
    /// Gets the <c>PrimCxnInputSize</c> L5X name value.
    ///</summary>
    public const string PrimCxnInputSize = "PrimCxnInputSize";
        
    ///<summary>
    /// Gets the <c>PrimCxnOutputSize</c> L5X name value.
    ///</summary>
    public const string PrimCxnOutputSize = "PrimCxnOutputSize";
        
    ///<summary>
    /// Gets the <c>Priority</c> L5X name value.
    ///</summary>
    public const string Priority = "Priority";
        
    ///<summary>
    /// Gets the <c>Priority1</c> L5X name value.
    ///</summary>
    public const string Priority1 = "Priority1";
        
    ///<summary>
    /// Gets the <c>Priority2</c> L5X name value.
    ///</summary>
    public const string Priority2 = "Priority2";
        
    ///<summary>
    /// Gets the <c>ProcessorType</c> L5X name value.
    ///</summary>
    public const string ProcessorType = "ProcessorType";
        
    ///<summary>
    /// Gets the <c>ProductCode</c> L5X name value.
    ///</summary>
    public const string ProductCode = "ProductCode";
        
    ///<summary>
    /// Gets the <c>ProductType</c> L5X name value.
    ///</summary>
    public const string ProductType = "ProductType";
        
    ///<summary>
    /// Gets the <c>ProgAck</c> L5X name value.
    ///</summary>
    public const string ProgAck = "ProgAck";
        
    ///<summary>
    /// Gets the <c>ProgAckAll</c> L5X name value.
    ///</summary>
    public const string ProgAckAll = "ProgAckAll";
        
    ///<summary>
    /// Gets the <c>ProgDisable</c> L5X name value.
    ///</summary>
    public const string ProgDisable = "ProgDisable";
        
    ///<summary>
    /// Gets the <c>ProgEnable</c> L5X name value.
    ///</summary>
    public const string ProgEnable = "ProgEnable";
        
    ///<summary>
    /// Gets the <c>Program</c> L5X name value.
    ///</summary>
    public const string Program = "Program";
        
    ///<summary>
    /// Gets the <c>ProgrammaticallySendEventTrigger</c> L5X name value.
    ///</summary>
    public const string ProgrammaticallySendEventTrigger = "ProgrammaticallySendEventTrigger";
        
    ///<summary>
    /// Gets the <c>Programs</c> L5X name value.
    ///</summary>
    public const string Programs = "Programs";
        
    ///<summary>
    /// Gets the <c>ProgReset</c> L5X name value.
    ///</summary>
    public const string ProgReset = "ProgReset";
        
    ///<summary>
    /// Gets the <c>ProgSuppress</c> L5X name value.
    ///</summary>
    public const string ProgSuppress = "ProgSuppress";
        
    ///<summary>
    /// Gets the <c>ProgTime</c> L5X name value.
    ///</summary>
    public const string ProgTime = "ProgTime";
        
    ///<summary>
    /// Gets the <c>ProgUnshelve</c> L5X name value.
    ///</summary>
    public const string ProgUnshelve = "ProgUnshelve";
        
    ///<summary>
    /// Gets the <c>ProgUnshelveAll</c> L5X name value.
    ///</summary>
    public const string ProgUnshelveAll = "ProgUnshelveAll";
        
    ///<summary>
    /// Gets the <c>ProgUnsuppress</c> L5X name value.
    ///</summary>
    public const string ProgUnsuppress = "ProgUnsuppress";
        
    ///<summary>
    /// Gets the <c>ProjectCreationDate</c> L5X name value.
    ///</summary>
    public const string ProjectCreationDate = "ProjectCreationDate";
        
    ///<summary>
    /// Gets the <c>ProjectSN</c> L5X name value.
    ///</summary>
    public const string ProjectSN = "ProjectSN";
        
    ///<summary>
    /// Gets the <c>PTPEnable</c> L5X name value.
    ///</summary>
    public const string PTPEnable = "PTPEnable";
        
    ///<summary>
    /// Gets the <c>QuickWatchList</c> L5X name value.
    ///</summary>
    public const string QuickWatchList = "QuickWatchList";
        
    ///<summary>
    /// Gets the <c>QuickWatchLists</c> L5X name value.
    ///</summary>
    public const string QuickWatchLists = "QuickWatchLists";
        
    ///<summary>
    /// Gets the <c>Radix</c> L5X name value.
    ///</summary>
    public const string Radix = "Radix";
        
    ///<summary>
    /// Gets the <c>Rate</c> L5X name value.
    ///</summary>
    public const string Rate = "Rate";
        
    ///<summary>
    /// Gets the <c>RedundancyInfo</c> L5X name value.
    ///</summary>
    public const string RedundancyInfo = "RedundancyInfo";
        
    ///<summary>
    /// Gets the <c>ReportMinorOverflow</c> L5X name value.
    ///</summary>
    public const string ReportMinorOverflow = "ReportMinorOverflow";
        
    ///<summary>
    /// Gets the <c>RequestedLength</c> L5X name value.
    ///</summary>
    public const string RequestedLength = "RequestedLength";
        
    ///<summary>
    /// Gets the <c>Required</c> L5X name value.
    ///</summary>
    public const string Required = "Required";
        
    ///<summary>
    /// Gets the <c>Revision</c> L5X name value.
    ///</summary>
    public const string Revision = "Revision";
        
    ///<summary>
    /// Gets the <c>RevisionExtension</c> L5X name value.
    ///</summary>
    public const string RevisionExtension = "RevisionExtension";
        
    ///<summary>
    /// Gets the <c>RevisionNote</c> L5X name value.
    ///</summary>
    public const string RevisionNote = "RevisionNote";
        
    ///<summary>
    /// Gets the <c>RLLContent</c> L5X name value.
    ///</summary>
    public const string RLLContent = "RLLContent";
        
    ///<summary>
    /// Gets the <c>ROCNegLimit</c> L5X name value.
    ///</summary>
    public const string ROCNegLimit = "ROCNegLimit";
        
    ///<summary>
    /// Gets the <c>ROCNegOperAck</c> L5X name value.
    ///</summary>
    public const string ROCNegOperAck = "ROCNegOperAck";
        
    ///<summary>
    /// Gets the <c>ROCNegOperShelve</c> L5X name value.
    ///</summary>
    public const string ROCNegOperShelve = "ROCNegOperShelve";
        
    ///<summary>
    /// Gets the <c>ROCNegOperUnshelve</c> L5X name value.
    ///</summary>
    public const string ROCNegOperUnshelve = "ROCNegOperUnshelve";
        
    ///<summary>
    /// Gets the <c>ROCNegProgAck</c> L5X name value.
    ///</summary>
    public const string ROCNegProgAck = "ROCNegProgAck";
        
    ///<summary>
    /// Gets the <c>ROCNegSeverity</c> L5X name value.
    ///</summary>
    public const string ROCNegSeverity = "ROCNegSeverity";
        
    ///<summary>
    /// Gets the <c>ROCPeriod</c> L5X name value.
    ///</summary>
    public const string ROCPeriod = "ROCPeriod";
        
    ///<summary>
    /// Gets the <c>ROCPosLimit</c> L5X name value.
    ///</summary>
    public const string ROCPosLimit = "ROCPosLimit";
        
    ///<summary>
    /// Gets the <c>ROCPosOperAck</c> L5X name value.
    ///</summary>
    public const string ROCPosOperAck = "ROCPosOperAck";
        
    ///<summary>
    /// Gets the <c>ROCPosOperShelve</c> L5X name value.
    ///</summary>
    public const string ROCPosOperShelve = "ROCPosOperShelve";
        
    ///<summary>
    /// Gets the <c>ROCPosOperUnshelve</c> L5X name value.
    ///</summary>
    public const string ROCPosOperUnshelve = "ROCPosOperUnshelve";
        
    ///<summary>
    /// Gets the <c>ROCPosProgAck</c> L5X name value.
    ///</summary>
    public const string ROCPosProgAck = "ROCPosProgAck";
        
    ///<summary>
    /// Gets the <c>ROCPosSeverity</c> L5X name value.
    ///</summary>
    public const string ROCPosSeverity = "ROCPosSeverity";
        
    ///<summary>
    /// Gets the <c>Routine</c> L5X name value.
    ///</summary>
    public const string Routine = "Routine";
        
    ///<summary>
    /// Gets the <c>Routines</c> L5X name value.
    ///</summary>
    public const string Routines = "Routines";
        
    ///<summary>
    /// Gets the <c>RPI</c> L5X name value.
    ///</summary>
    public const string RPI = "RPI";
        
    ///<summary>
    /// Gets the <c>RSLogix5000Content</c> L5X name value.
    ///</summary>
    public const string RSLogix5000Content = "RSLogix5000Content";
        
    ///<summary>
    /// Gets the <c>Rung</c> L5X name value.
    ///</summary>
    public const string Rung = "Rung";
        
    ///<summary>
    /// Gets the <c>SafetyEnabled</c> L5X name value.
    ///</summary>
    public const string SafetyEnabled = "SafetyEnabled";
        
    ///<summary>
    /// Gets the <c>SafetyInfo</c> L5X name value.
    ///</summary>
    public const string SafetyInfo = "SafetyInfo";
        
    ///<summary>
    /// Gets the <c>ScheduledProgram</c> L5X name value.
    ///</summary>
    public const string ScheduledProgram = "ScheduledProgram";
        
    ///<summary>
    /// Gets the <c>ScheduledPrograms</c> L5X name value.
    ///</summary>
    public const string ScheduledPrograms = "ScheduledPrograms";
        
    ///<summary>
    /// Gets the <c>SchemaRevision</c> L5X name value.
    ///</summary>
    public const string SchemaRevision = "SchemaRevision";
        
    ///<summary>
    /// Gets the <c>Scope</c> L5X name value.
    ///</summary>
    public const string Scope = "Scope";
        
    ///<summary>
    /// Gets the <c>Security</c> L5X name value.
    ///</summary>
    public const string Security = "Security";
        
    ///<summary>
    /// Gets the <c>ServiceCode</c> L5X name value.
    ///</summary>
    public const string ServiceCode = "ServiceCode";
        
    ///<summary>
    /// Gets the <c>Severity</c> L5X name value.
    ///</summary>
    public const string Severity = "Severity";
        
    ///<summary>
    /// Gets the <c>SFCExecutionControl</c> L5X name value.
    ///</summary>
    public const string SFCExecutionControl = "SFCExecutionControl";
        
    ///<summary>
    /// Gets the <c>SFCLastScan</c> L5X name value.
    ///</summary>
    public const string SFCLastScan = "SFCLastScan";
        
    ///<summary>
    /// Gets the <c>SFCRestartPosition</c> L5X name value.
    ///</summary>
    public const string SFCRestartPosition = "SFCRestartPosition";

    ///<summary>
    /// Gets the <c>TimeSlice</c> L5X name value.
    ///</summary>
    public const string ShareUnusedTimeSlice = "ShareUnusedTimeSlice";

    ///<summary>
    /// Gets the <c>ShelveDuration</c> L5X name value.
    ///</summary>
    public const string ShelveDuration = "ShelveDuration";

    ///<summary>
    /// Gets the <c>ShutdownParentOnFault</c> L5X name value.
    ///</summary>
    public const string ShutdownParentOnFault = "ShutdownParentOnFault";

    ///<summary>
    /// Gets the <c>Size</c> L5X name value.
    ///</summary>
    public const string Size = "Size";

    ///<summary>
    /// Gets the <c>SoftwareRevision</c> L5X name value.
    ///</summary>
    public const string SoftwareRevision = "SoftwareRevision";

    ///<summary>
    /// Gets the <c>Specifier</c> L5X name value.
    ///</summary>
    public const string Specifier = "Specifier";

    ///<summary>
    /// Gets the <c>State</c> L5X name value.
    ///</summary>
    public const string State = "State";

    ///<summary>
    /// Gets the <c>RLLContent</c> L5X name value.
    ///</summary>
    public const string STContent = "STContent";

    ///<summary>
    /// Gets the <c>Structure</c> L5X name value.
    ///</summary>
    public const string Structure = "Structure";

    ///<summary>
    /// Gets the <c>StructureMember</c> L5X name value.
    ///</summary>
    public const string StructureMember = "StructureMember";

    ///<summary>
    /// Gets the <c>Tag</c> L5X name value.
    ///</summary>
    public const string Tag = "Tag";

    ///<summary>
    /// Gets the <c>Tags</c> L5X name value.
    ///</summary>
    public const string Tags = "Tags";

    ///<summary>
    /// Gets the <c>TagType</c> L5X name value.
    ///</summary>
    public const string TagType = "TagType";

    ///<summary>
    /// Gets the <c>Target</c> L5X name value.
    ///</summary>
    public const string Target = "Target";

    ///<summary>
    /// Gets the <c>TargetName</c> L5X name value.
    ///</summary>
    public const string TargetName = "TargetName";

    ///<summary>
    /// Gets the <c>TargetObject</c> L5X name value.
    ///</summary>
    public const string TargetObject = "TargetObject";

    ///<summary>
    /// Gets the <c>TargetType</c> L5X name value.
    ///</summary>
    public const string TargetType = "TargetType";

    ///<summary>
    /// Gets the <c>Task</c> L5X name value.
    ///</summary>
    public const string Task = "Task";

    ///<summary>
    /// Gets the <c>Tasks</c> L5X name value.
    ///</summary>
    public const string Tasks = "Tasks";

    ///<summary>
    /// Gets the <c>TestEdits</c> L5X name value.
    ///</summary>
    public const string TestEdits = "TestEdits";

    ///<summary>
    /// Gets the <c>Text</c> L5X name value.
    ///</summary>
    public const string Text = "Text";

    ///<summary>
    /// Gets the <c>TimeSlice</c> L5X name value.
    ///</summary>
    public const string TimeSlice = "TimeSlice";

    ///<summary>
    /// Gets the <c>TimeSyncEnabled</c> L5X name value.
    ///</summary>
    public const string TimeSyncEnabled = "TimeSyncEnabled";

    ///<summary>
    /// Gets the <c>TimeSynchronize</c> L5X name value.
    ///</summary>
    public const string TimeSynchronize = "TimeSynchronize";

    ///<summary>
    /// Gets the <c>TimeZone</c> L5X name value.
    ///</summary>
    public const string TimeZone = "TimeZone";

    ///<summary>
    /// Gets the <c>Trend</c> L5X name value.
    ///</summary>
    public const string Trend = "Trend";

    ///<summary>
    /// Gets the <c>Trends</c> L5X name value.
    ///</summary>
    public const string Trends = "Trends";

    ///<summary>
    /// Gets the <c>Type</c> L5X name value.
    ///</summary>
    public const string Type = "Type";

    ///<summary>
    /// Gets the <c>Unicast</c> L5X name value.
    ///</summary>
    public const string Unicast = "Unicast";

    ///<summary>
    /// Gets the <c>Upstream</c> L5X name value.
    ///</summary>
    public const string Upstream = "Upstream";

    ///<summary>
    /// Gets the <c>Usage</c> L5X name value.
    ///</summary>
    public const string Usage = "Usage";

    ///<summary>
    /// Gets the <c>Use</c> L5X name value.
    ///</summary>
    public const string Use = "Use";

    ///<summary>
    /// Gets the <c>UseAsFolder</c> L5X name value.
    ///</summary>
    public const string UseAsFolder = "UseAsFolder";

    ///<summary>
    /// Gets the <c>UseProgTime</c> L5X name value.
    ///</summary>
    public const string UseProgTime = "UseProgTime";

    ///<summary>
    /// Gets the <c>UserDefinedCatalogNumber</c> L5X name value.
    ///</summary>
    public const string UserDefinedCatalogNumber = "UserDefinedCatalogNumber";

    ///<summary>
    /// Gets the <c>UserDefinedMajor</c> L5X name value.
    ///</summary>
    public const string UserDefinedMajor = "UserDefinedMajor";

    ///<summary>
    /// Gets the <c>UserDefinedMinor</c> L5X name value.
    ///</summary>
    public const string UserDefinedMinor = "UserDefinedMinor";

    ///<summary>
    /// Gets the <c>UserDefinedProductCode</c> L5X name value.
    ///</summary>
    public const string UserDefinedProductCode = "UserDefinedProductCode";

    ///<summary>
    /// Gets the <c>UserDefinedProductType</c> L5X name value.
    ///</summary>
    public const string UserDefinedProductType = "UserDefinedProductType";

    ///<summary>
    /// Gets the <c>UserDefinedVendor</c> L5X name value.
    ///</summary>
    public const string UserDefinedVendor = "UserDefinedVendor";

    ///<summary>
    /// Gets the <c>Value</c> L5X name value.
    ///</summary>
    public const string Value = "Value";

    ///<summary>
    /// Gets the <c>Vendor</c> L5X name value.
    ///</summary>
    public const string Vendor = "Vendor";

    ///<summary>
    /// Gets the <c>Version</c> L5X name value.
    ///</summary>
    public const string Version = "Version";

    ///<summary>
    /// Gets the <c>Visible</c> L5X name value.
    ///</summary>
    public const string Visible = "Visible";

    ///<summary>
    /// Gets the <c>WallClockTime</c> L5X name value.
    ///</summary>
    public const string WallClockTime = "WallClockTime";

    ///<summary>
    /// Gets the <c>Watchdog</c> L5X name value.
    ///</summary>
    public const string Watchdog = "Watchdog";

    ///<summary>
    /// Gets the <c>WatchTag</c> L5X name value.
    ///</summary>
    public const string WatchTag = "WatchTag";
}