using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Xml.Linq;
using L5Sharp.Components;
using L5Sharp.Core;
using L5Sharp.Extensions;
using L5Sharp.Serialization;
using L5Sharp.Utilities;

namespace L5Sharp
{
    /// <summary>
    /// A simple wrapper around a given <see cref="XElement"/>, which is expected to be the root RSLogix5000Content element
    /// of the L5X file. This class implements <see cref="ILogixContent"/> API.
    /// </summary>
    public class LogixContent : ILogixContent
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="element"></param>
        /// <exception cref="ArgumentNullException"></exception>
        private LogixContent(XElement element)
        {
            if (element is null)
                throw new ArgumentNullException(nameof(element));

            if (element.Name != L5XName.RSLogix5000Content)
                throw new ArgumentException($"Expecting root element name of {L5XName.RSLogix5000Content}.");

            L5X = new L5X(element);
        }

        /// <summary>
        /// Creates a new <see cref="LogixContent"/> by loading the contents of the provide file name.
        /// </summary>
        /// <param name="fileName">The full path, including file name, to the L5X file to load.</param>
        /// <returns>A new <see cref="LogixContent"/> containing the contents of the specified file.</returns>
        /// <exception cref="ArgumentException">The string is null or empty.</exception>
        /// <remarks>
        /// This factory method uses the <see cref="XDocument.Load(string)"/> to load the contents of the xml file into
        /// memory. This means that this method is subject to the same exceptions that could be generated by loading the
        /// XDocument. Once loaded, validation is performed to ensure the content adheres to the specified L5X Schema files.
        /// </remarks>
        public static LogixContent Load(string fileName) => new(XElement.Load(fileName));

        /// <summary>
        /// Creates a new <see cref="LogixContent"/> with the provided L5X string content.
        /// </summary>
        /// <param name="text">The string that contains the L5X content to parse.</param>
        /// <returns>A new <see cref="LogixContent"/> containing the contents of the specified string.</returns>
        /// <exception cref="ArgumentException">The string is null or empty.</exception>
        /// <remarks>
        /// This factory method uses the <see cref="XDocument.Parse(string)"/> to load the contents of the xml file into
        /// memory. This means that this method is subject to the same exceptions that could be generated by parsing the
        /// XDocument. Once parsed, validation is performed to ensure the content adheres to the specified L5X Schema files.
        /// </remarks>
        public static LogixContent Parse(string text) => new(XElement.Parse(text));

        /// <summary>
        /// 
        /// </summary>
        public L5X L5X { get; }

        /// <inheritdoc />
        public Controller? Controller()
        {
            var element = L5X.Element(L5XName.Controller);
            return element is not null ? LogixSerializer.Deserialize<Controller>(element) : null;
        }

        /// <inheritdoc />
        public ILogixComponentCollection<DataType> DataTypes()
        {
            var container = L5X.Descendants(L5XName.DataTypes).FirstOrDefault() ?? new XElement(L5XName.DataTypes);
            return new ComponentCollection<DataType>(container);
        }

        /// <inheritdoc />
        public ILogixComponentCollection<AddOnInstruction> Instructions()
        {
            var container = L5X.Descendants(L5XName.AddOnInstructionDefinitions).FirstOrDefault() ??
                            new XElement(L5XName.AddOnInstructionDefinitions);
            return new ComponentCollection<AddOnInstruction>(container);
        }

        /// <inheritdoc />
        public ILogixComponentCollection<Module> Modules()
        {
            var container = L5X.Descendants(L5XName.Modules).FirstOrDefault() ?? new XElement(L5XName.Modules);
            return new ComponentCollection<Module>(container);
        }

        /// <inheritdoc />
        public ILogixComponentCollection<Program> Programs()
        {
            var container = L5X.Descendants(L5XName.Programs).FirstOrDefault() ?? new XElement(L5XName.Programs);
            return new ComponentCollection<Program>(container);
        }

        /// <inheritdoc />
        public ILogixComponentCollection<Tag> Tags()
        {
            var container = L5X.Descendants(L5XName.Tags).FirstOrDefault() ?? new XElement(L5XName.Tags);
            return new ComponentCollection<Tag>(container);
        }

        /// <inheritdoc />
        public ILogixComponentCollection<Tag> Tags(string scope)
        {
            var scopedContainer = L5X.Descendants().FirstOrDefault(e => e.LogixName() == scope);

            if (scopedContainer is null)
                throw new InvalidOperationException();

            var container = scopedContainer.Descendants(L5XName.Tags).FirstOrDefault() ?? new XElement(L5XName.Tags);
            return new ComponentCollection<Tag>(container);
        }

        /// <inheritdoc />
        public ILogixComponentCollection<Routine> Routines(string scope)
        {
            var scopedContainer =
                L5X.Descendants(L5XName.Program).FirstOrDefault(e => e.LogixName() == scope) ??
                L5X.Descendants(L5XName.AddOnInstructionDefinition).FirstOrDefault(e => e.LogixName() == scope);
            
            if (scopedContainer is null)
                throw new InvalidOperationException();
            
            var container = scopedContainer.Descendants(L5XName.Routines).FirstOrDefault();
            return new ComponentCollection<Routine>(container);
        }

        /// <inheritdoc />
        public ILogixComponentCollection<TRoutine> Routines<TRoutine>(string scope) where TRoutine : Routine
        {
            var scopedContainer =
                L5X.Descendants(L5XName.Program).FirstOrDefault(e => e.LogixName() == scope) ??
                L5X.Descendants(L5XName.AddOnInstructionDefinition).FirstOrDefault(e => e.LogixName() == scope);
            
            if (scopedContainer is null)
                throw new InvalidOperationException();
            
            var container = scopedContainer.Descendants(L5XName.Routines).FirstOrDefault();
            return new ComponentCollection<TRoutine>(container);
        }

        /// <inheritdoc />
        public ILogixComponentCollection<Task> Tasks()
        {
            var container = L5X.Descendants(L5XName.Tasks).FirstOrDefault() ?? new XElement(L5XName.Tasks);
            return new ComponentCollection<Task>(container);
        }

        /// <inheritdoc />
        public IEnumerable<TEntity> Query<TEntity>()
        {
            throw new NotImplementedException();
        }

        /// <inheritdoc />
        public IEnumerable<TEntity> Query<TEntity>(Expression<Func<TEntity, bool>> predicate)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Serialize this <see cref="LogixContent"/> to a file, overwriting an existing file, if it exists.
        /// </summary>
        /// <param name="fileName">A string that contains the name of the file.</param>
        public void Save(string fileName)
        {
            var declaration = new XDeclaration("1.0", "UTF-8", "yes");
            var document = new XDocument(declaration);
            document.Add(L5X);
            document.Save(fileName);
        }

        /// <inheritdoc />
        public override string ToString() => L5X.ToString();

        private static XElement CreateContent<TComponent>(TComponent target) where TComponent : ILogixComponent
        {
            var content = new XElement(L5XName.RSLogix5000Content);

            content.Add(new XAttribute(L5XName.SchemaRevision, new Revision().ToString()));
            content.Add(new XAttribute(L5XName.TargetName, target.Name));
            content.Add(new XAttribute(L5XName.TargetType, target.GetType()));
            content.Add(new XAttribute(L5XName.ContainsContext, target.Name != L5XName.Controller));
            content.Add(new XAttribute(L5XName.Owner, Environment.UserName));
            //content.Add(new XAttribute(L5XName.ExportDate, DateTime.Now.ToString(DateFormat)));

            //todo this would depend on the component. data type, instruction, module, program, etc...
            var serializer = LogixSerializer.GetSerializer<TComponent>();
            var component = serializer.Serialize(target);
            content.Add(component);

            return content;
        }
    }
}